#ACCION HEROICA
ENERGIA_ACCION_HEROICA = 10
POPULARIDAD_ACCION_HEROICA = 11

#ATACAR TRIBUTO
ENERGIA_ATACAR = 12
POPULARIDAD_ATACAR = 13

#PEDIR OBJETO
COSTO_OBJETO = 4

#BOLITA
ENERGIA_BOLITA = 15

#EVENTO 
PROBABILIDAD_EVENTO = 50

#PLAYA
VELOCIDAD_VIENTOS_PLAYA = 100
HUMEDAD_PLAYA = 120

#MONTANA
NUBOSIDAD_MONTANA = 130
PRECIPITACIONES_MONTANA = 160

#BOSQUE
PRECIPITACIONES_BOSQUE = 150
VELOCIDAD_VIENTOS_BOSQUE = 60

AUMENTAR_ENERGIA = 12
PONDERADOR_AUMENTAR_FUERZA = 17
AUMENTAR_AGILIDAD = 11
AUMENTAR_INGENIO = 13
 