openapi: 3.0.0
info:
  title: API Endpoint Documentation for users routes
  version: 1.0.0
paths:
  /api/users/login:
    post:
      summary: User Login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        200:
          description: User logged in successfully. The user is not blocked.
          content:
            application/json:
              schema:
                type: object
                properties:
                  administrator:
                    type: boolean
                  userId:
                    type: integer
        400:
          description: Bad Request. The request body is missing required fields or contains invalid data.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseBody'
        403:
          description: Forbidden. The user is blocked and cannot log in.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseBody'
        404:
          description: Not Found. User not found or incorrect password.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseBody'
        500:
          description: Internal Server Error. An error occurred while processing the login request.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseBody'

  /api/users:
    post:
      summary: Create a New User
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateUserRequestBody'
      responses:
        201:
          description: User created successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        400:
          description: Bad Request. The request body is missing required fields or contains invalid data.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseBody'
        500:
          description: Internal Server Error. An error occurred while creating the user.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseBody'

  /api/users/{id}:
    get:
      summary: Retrieve a User by ID
      parameters:
        - $ref: '#/components/parameters/UserIdParam'
      responses:
        200:
          description: User retrieved successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        404:
          description: Not Found. User not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseBody'
        500:
          description: Internal Server Error. An error occurred while retrieving the user.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseBody'

    put:
      summary: Update a User by ID
      parameters:
        - $ref: '#/components/parameters/UserIdParam'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
                type:
                  type: string
      responses:
        200:
          description: User updated successfully.
          content:
            application/json:
              schema:
              type: object
              properties:
                password:
                  type: string
                newPassword:
                  type: string'
        400:
          description: Bad Request. The request body is missing required fields or contains invalid data.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseBody'
        404:
          description: Not Found. User not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseBody'
        500:
          description: Internal Server Error. An error occurred while updating the user.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseBody'

    delete:
      summary: Delete a User by ID
      parameters:
        - $ref: '#/components/parameters/UserIdParam'
      responses:
        204:
          description: User deleted successfully.
        404:
          description: Not Found. User not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseBody'
        500:
          description: Internal Server Error. An error occurred while deleting the user.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseBody'
        
  /api/users/changePassword/{id}:
    put:
      summary: Change User Password
      parameters:
        - $ref: '#/components/parameters/UserIdParam'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChangePasswordBody'
      responses:
        200:
          description: Password changed successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        400:
          description: Bad Request. The request body is missing required fields or contains invalid data.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseBody'
        404:
          description: Not Found. User not found or incorrect previous password.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseBody'
        500:
          description: Internal Server Error. An error occurred while changing the password.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseBody'
components:
  schemas:
    ErrorResponseBody:
      type: object
      properties:
        error:
          type: string